### ISSUE TITLE
unable to open file after running transcribe_audio.sh

### ISSUE THREAD

**Issue by CryptoKR** [BreezeWhite/Music-Transcription-with-Semantic-Segmentation#11]
I ran transcribe_audio.sh and got error below:

bash transcribe_audio.sh
Using TensorFlow backend.
Processing features of input audio: sample_audio.wav
Sample:  12193
Traceback (most recent call last):
  File "SingleSongTest.py", line 78, in <module>
    main(args)
  File "SingleSongTest.py", line 44, in main
    model = load_model(args.model_path)
  File "/home/kr/Downloads/Music-Transcription-with-Semantic-Segmentation/project/utils.py", line 101, in load_model
    with h5py.File(full_path, "r") as w:
  File "/home/kr/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/kr/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

Am I doing it correctly?

**Comment by BreezeWhite** [comment]
You have to modify the model path at line 8 of `transcribe_audio.sh`. 
Change it to `CheckPoint/Maestro-Note` and try again.
